version: "2"
run:
  timeout: 2m
formatters:
  enable:
    # Configuration of golang imports with wpe requirements.
    - gci
    # Code should be always gofmted
    # gofumpt is stricter than gofmt but works well together
    - gofmt
    - goimports
    - golines
    # gofumpt is stricter than gofmt but works well together
    - gofumpt
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - mnd
    - paralleltest
    - wrapcheck
  settings:
    revive:
      rules:
        - name: dot-imports
          disabled: true
    sloglint:
      # Enforce using attributes only (overrides no-mixed-args, incompatible with kv-only).
      attr-only: true
      # Enforce using methods that accept a context.
      context: scope
      # Enforce using static values for log messages.
      static-msg: true
      # Enforce a single key naming convention.
      key-naming-case: camel
      # Enforce putting arguments on separate lines.
      args-on-sep-lines: true
      # Don't use the global slog logger
      no-global: all
    importas:
      alias:
        - pkg: github.com/tydanny/foodwheel/gen/cuisines/v1
          alias: cuisinesv1
