name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
        
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.51.2
      
    - name: Test
      run: make test

    - name: Build
      run: make build
